version: '3'
services:
  jenkins:
    image: my-custom-jenkins  # updated to use the local image
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../docker-volumes/jenkins-volume:/var/jenkins_home  # Your specific path can be different
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin_password
    container_name: jenkins-server
