entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  insecure: true


certificatesResolvers:
  letsencrypt:
    acme:
      email: "rutvik2611@gmail.com"
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 1s
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
  myresolver:
    acme:
      email: "rutvik2611@gmail.com"
      storage: acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: letsencrypt
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"