entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: ./config.yml

api:
  insecure: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: rutvik2611@gmail.com
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web
#   local:
#     file:
#       filename: /etc/traefik/self-signed-certificates/certificates.toml
#       watch: true
