version: '3.1'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: yourusername
            POSTGRES_PASSWORD: yourpassword
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.db.rule=Host(`db.127.0.0.1.nip.io`)"
            - "traefik.http.services.db.loadbalancer.server.port=5432"

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: user@example.com
            PGADMIN_DEFAULT_PASSWORD: secret
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.127.0.0.1.nip.io`)"
            - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

volumes:
    postgres_data:

networks:
    default:
        external: true
        name: my_network