version: '3.1'

services:
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: user@example.com
            PGADMIN_DEFAULT_PASSWORD: secret
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.pgadmin.rule=Host('localhost')"
            - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
        depends_on:
            - db

networks:
    default:
        external: true
        name: my_network
