version: '3.1'

services:
    portainer:
        image: portainer/portainer-ce
        command: -H unix:///var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)"
            - "traefik.http.services.portainer.loadbalancer.server.port=9000"

volumes:
    portainer_data:

networks:
    default:
        external: true
        name: my_network