version: '3.1'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # ports:
    #   - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.db.rule=Host(`db.${DOMAIN}`)"
      - "traefik.http.services.db.loadbalancer.server.port=5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.127.0.0.1.nip.io`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

networks:
  default:
    external: true
    name: my_network

volumes:
  postgres_data: