version: '3.1'

services:
  grafana:
    image: grafana/grafana:latest
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana.middlewares=redirectScheme@file"
      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.${DOMAIN}`)"
      - "traefik.http.routers.grafana-secure.entrypoints=websecure"
      - "traefik.http.routers.grafana-secure.tls.certresolver=letsencrypt"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: secret

volumes:
  grafana-storage:

networks:
  default:
    external:
      name: my_network