version: '3.1'

services:
  prometheus:
    image: prom/prometheus:latest
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN}`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.entrypoints=web,websecure"
      - "traefik.http.routers.prometheus.middlewares=redirectScheme@file"
      - "traefik.http.routers.prometheus.tls.certresolver=letsencrypt"
      
    volumes:
      - .prometheus/:/etc/prometheus/

networks:
  default:
    external: true
    name: my_network