version: '3.1'

services:
    portainer:
        image: portainer/portainer-ce
        command: -H unix:///var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./master/portainer:/data
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.portainer.rule=Host(`portainer.127.0.0.1.nip.io`)"
            - "traefik.http.services.portainer.loadbalancer.server.port=9000"
            - "traefik.http.routers.portainer.entrypoints=web,websecure"
            - "traefik.http.routers.portainer.middlewares=redirectScheme@file"
            - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
volumes:
    portainer_data:

networks:
    default:
        external: true
        name: my_network