version: '3.1'

services:
  traefik:
    image: traefik:v2.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./master/traefik/acme.json:/acme.json
      - ./master/traefik/config.yml:/config.yml
      - ./master/traefik/traefik.yml:/traefik.yml
      - ./master/traefik:/etc/traefik
    networks:
      - default

networks:
  default:
    external:
      name: my_network