version: '3.1'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # ports:
    #   - '5432:5432'
    volumes:
      - ./master/postgres:/var/lib/postgresql/data/
    networks:
      - default
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.db.rule=Host(`db.${DOMAIN}`)"
      - "traefik.http.services.db.loadbalancer.server.port=5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    networks:
      - default
    volumes:
      - ./master/pgadmin:/var/lib/pgadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.127.0.0.1.nip.io`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.pgadmin.entrypoints=web,websecure"
      - "traefik.http.routers.pgadmin.middlewares=redirectScheme@file"
      - "traefik.http.routers.pgadmin.tls.certresolver=letsencrypt"
networks:
  default:
    external: true
    name: my_network
