# version: '3'

# services:
#   authelia:
#     image: authelia/authelia
#     volumes:
#       - ./authelia:/config
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.authelia.rule=Host(`authelia.${DOMAIN}`)"
#       - "traefik.http.services.authelia.loadbalancer.server.port=9091"
#       - "traefik.http.routers.authelia.entrypoints=web,websecure"
#       - "traefik.http.routers.authelia.middlewares=redirectScheme@file"
#       - "traefik.http.routers.authelia.tls.certresolver=letsencrypt"
# networks:
#     default:
#         external: true
#         name: my_network